# Let NetworkManager manage all devices on this system
network:
  ethernets:
    ens33:
      dhcp4: false
      dhcp6: false
  version: 2

  bridges:
    br0:
      interfaces:
        - ens33
      addresses:
        - 10.1.1.21/24
      gateway4: 10.1.1.1
      nameservers:
        addresses: [10.1.1.1]
